from typing import Optional, List, Dict, Any, Union
from langchain_core.tools import tool
import digitalhub as dh


@tool
def new_dh_artifact(
    project: str,
    name: str,
    kind: str = "artifact",
    uuid: Optional[str] = None,
    description: Optional[str] = None,
    labels: Optional[List[str]] = None,
    embedded: bool = False,
    path: Optional[str] = None,
    extensions: Optional[List[dict]] = None,
    extra_specs: Optional[Dict[str, Any]] = None,
    **kwargs: Any,
):
    """
    Create a new Artifact entity in DigitalHub WITHOUT uploading file content.

    Registers a metadata-only reference pointing at an existing local or remote
    path (e.g. an existing s3:// object). 'path' becomes both the artifact's
    spec.path (source of downloads) and the default destination of upload().
    Kind-specific spec fields go inside 'extra_specs'.
    """
    raw_specs = extra_specs or kwargs.get("kwargs") or kwargs.get("v__kwargs") or {}
    if not isinstance(raw_specs, dict):
        raw_specs = {}
    spec_kwargs = {k: v for k, v in raw_specs.items() if k not in ("v__kwargs", "kwargs")}
    return dh.new_artifact(
        project=project,
        name=name,
        kind=kind,
        uuid=uuid,
        description=description,
        labels=labels,
        embedded=embedded,
        path=path,
        extensions=extensions,
        **spec_kwargs,
    )


@tool
def log_dh_artifact(
    project: str,
    name: str,
    source: Union[str, List[str]],
    kind: str = "artifact",
    drop_existing: bool = False,
    path: Optional[str] = None,
    description: Optional[str] = None,
    labels: Optional[List[str]] = None,
    extra_specs: Optional[Dict[str, Any]] = None,
    **kwargs: Any,
):
    """
    Log an artifact: create the entity AND upload the local file(s) to the artifact store.

    'source' can be a single local filepath, a directory, or a list of paths.
    'path' is the destination path in the artifact store; if not provided, it
    is auto-generated by the SDK.
    """
    raw_specs = extra_specs or kwargs.get("kwargs") or kwargs.get("v__kwargs") or {}
    if not isinstance(raw_specs, dict):
        raw_specs = {}
    spec_kwargs = {k: v for k, v in raw_specs.items() if k not in ("v__kwargs", "kwargs")}
    return dh.log_artifact(
        project=project,
        name=name,
        kind=kind,
        source=source,
        drop_existing=drop_existing,
        path=path,
        description=description,
        labels=labels,
        **spec_kwargs,
    )


@tool
def log_dh_generic_artifact(
    project: str,
    name: str,
    source: Union[str, List[str]],
    drop_existing: bool = False,
    path: Optional[str] = None,
    description: Optional[str] = None,
    labels: Optional[List[str]] = None,
    extra_specs: Optional[Dict[str, Any]] = None,
    **kwargs: Any,
):
    """
    Log a generic artifact (kind='artifact') from a local path to the artifact store.

    Convenience shortcut for log_dh_artifact when you don't need to specify a kind.
    """
    raw_specs = extra_specs or kwargs.get("kwargs") or kwargs.get("v__kwargs") or {}
    if not isinstance(raw_specs, dict):
        raw_specs = {}
    spec_kwargs = {k: v for k, v in raw_specs.items() if k not in ("v__kwargs", "kwargs")}
    return dh.log_generic_artifact(
        project=project,
        name=name,
        source=source,
        drop_existing=drop_existing,
        path=path,
        description=description,
        labels=labels,
        **spec_kwargs,
    )


@tool
def get_dh_artifact(
    identifier: str,
    project: Optional[str] = None,
    entity_id: Optional[str] = None,
):
    """
    Get an Artifact object from the backend.

    'identifier' can be an entity key (store://...) or the artifact name.
    """
    return dh.get_artifact(
        identifier=identifier,
        project=project,
        entity_id=entity_id,
    )


@tool
def get_dh_artifact_versions(
    identifier: str,
    project: Optional[str] = None,
):
    """
    Get all artifact version instances from the backend.
    """
    return dh.get_artifact_versions(
        identifier=identifier,
        project=project,
    )


@tool
def import_dh_artifact(
    file: Optional[str] = None,
    key: Optional[str] = None,
    reset_id: bool = False,
    context: Optional[str] = None,
):
    """
    Import an artifact object from a YAML file or from a storage key.
    """
    return dh.import_artifact(
        file=file,
        key=key,
        reset_id=reset_id,
        context=context,
    )


@tool
def list_dh_artifacts(
    project: str,
    q: Optional[str] = None,
    name: Optional[str] = None,
    kind: Optional[str] = None,
    user: Optional[str] = None,
    state: Optional[str] = None,
    created: Optional[str] = None,
    updated: Optional[str] = None,
    versions: Optional[str] = None,
):
    """
    List latest-version artifact objects from backend for a project with optional filters.
    """
    return dh.list_artifacts(
        project=project,
        q=q,
        name=name,
        kind=kind,
        user=user,
        state=state,
        created=created,
        updated=updated,
        versions=versions,
    )


@tool
def update_dh_artifact(
    project_name: str,
    name: str,
):
    """
    Update an artifact object in the backend. Note that object specs are immutable.
    """
    art = dh.get_artifact(name, project=project_name)
    return dh.update_artifact(art)


@tool
def delete_dh_artifact(
    identifier: str,
    project: Optional[str] = None,
    entity_id: Optional[str] = None,
    delete_all_versions: bool = False,
    cascade: bool = True,
):
    """
    Delete an artifact object from backend.
    """
    return dh.delete_artifact(
        identifier=identifier,
        project=project,
        entity_id=entity_id,
        delete_all_versions=delete_all_versions,
        cascade=cascade,
    )


@tool
def save_dh_artifact(
    project_name: str,
    name: str,
    update: bool = False,
):
    """
    Save or update the artifact entity into the backend.
    """
    art = dh.get_artifact(name, project=project_name)
    return art.save(update=update)


@tool
def refresh_dh_artifact(
    project_name: str,
    name: str,
):
    """
    Refresh artifact state from backend.
    """
    art = dh.get_artifact(name, project=project_name)
    return art.refresh()


@tool
def export_dh_artifact(
    project_name: str,
    name: str,
):
    """
    Export artifact object as a YAML file in the context folder.
    """
    art = dh.get_artifact(name, project=project_name)
    return art.export()


@tool
def as_file_dh_artifact(
    project_name: str,
    name: str,
):
    """
    Download the artifact into a temporary folder and return the list of file paths.

    Useful for immediate consumption (e.g. read/parse) without choosing a destination.
    """
    art = dh.get_artifact(name, project=project_name)
    return art.as_file()


@tool
def download_dh_artifact(
    project_name: str,
    name: str,
    destination: Optional[str] = None,
    overwrite: bool = False,
):
    """
    Download the artifact's file(s) from storage to a local path.

    If 'destination' is not specified, files are placed under the context path.
    If files already exist and overwrite=False, an error is raised.
    """
    art = dh.get_artifact(name, project=project_name)
    return art.download(destination=destination, overwrite=overwrite)


@tool
def upload_dh_artifact(
    project_name: str,
    name: str,
    source: Union[str, List[str]],
    keep_dir_structure: bool = False,
):
    """
    Upload local file(s) to the artifact's spec.path in remote storage.

    'source' can be a filepath, a directory, or a list of paths.
    When 'source' is a directory or list, spec.path must be a folder/partition
    ending with '/' (for s3).
    """
    art = dh.get_artifact(name, project=project_name)
    return art.upload(source, keep_dir_structure=keep_dir_structure)


ARTIFACT_TOOLS = [
    new_dh_artifact,
    log_dh_artifact,
    log_dh_generic_artifact,
    get_dh_artifact,
    get_dh_artifact_versions,
    import_dh_artifact,
    list_dh_artifacts,
    update_dh_artifact,
    delete_dh_artifact,
    save_dh_artifact,
    refresh_dh_artifact,
    export_dh_artifact,
    as_file_dh_artifact,
    download_dh_artifact,
    upload_dh_artifact,
]
